/**
 * Documentation pages on atproto.com and docs.bsky.app.
 *
 * GENERATED by scripts/build-docs-manifest.mjs. Do not hand-edit: regenerate
 * it when upstream adds or renames pages. 106 entries, last built 2026-08-26.
 *
 * This is an index, not a copy: bodies are fetched from the raw CDN at request
 * time so answers track upstream, while ranking a query stays local.
 */

export type DocSource = 'atproto' | 'bsky';

export type DocPage = {
  /** Stable id a caller passes to read_atproto_doc. */
  id: string;
  source: DocSource;
  title: string;
  description: string;
  /** The public page, for citation. */
  url: string;
  /** Where the Markdown actually comes from. */
  raw: string;
  headings: string[];
};

export const DOC_PAGES: DocPage[] = [
  {
    "id": "bsky/advanced-guides/api-directory",
    "source": "bsky",
    "title": "API Hosts and Auth",
    "description": "Lexicon API definitions do not always indicate which network services implement the endpoint, and whether auth is required when making HTTP requests. This guide describes the most common API request patterns, and lists …",
    "url": "https://docs.bsky.app/docs/advanced-guides/api-directory",
    "raw": "https://raw.githubusercontent.com/bluesky-social/bsky-docs/main/docs/advanced-guides/api-directory.mdx",
    "headings": [
      "Common Request Types",
      "Other Request Types",
      "Bluesky Services"
    ]
  },
  {
    "id": "bsky/advanced-guides/atproto",
    "source": "bsky",
    "title": "The AT Protocol",
    "description": "The AT Protocol (Authenticated Transfer Protocol, or atproto) is a standard for public conversation and an open-source framework for building social apps.",
    "url": "https://docs.bsky.app/docs/advanced-guides/atproto",
    "raw": "https://raw.githubusercontent.com/bluesky-social/bsky-docs/main/docs/advanced-guides/atproto.md",
    "headings": [
      "Basic Concepts",
      "Identity",
      "Data repositories",
      "Federation",
      "Interoperation",
      "Achieving scale",
      "Algorithmic choice",
      "Account portability",
      "Speech, reach, and moderation",
      "Read More"
    ]
  },
  {
    "id": "bsky/advanced-guides/backfill",
    "source": "bsky",
    "title": "Backfilling the Network",
    "description": "Backfilling is the process of syncing all the data in the network from scratch.",
    "url": "https://docs.bsky.app/docs/advanced-guides/backfill",
    "raw": "https://raw.githubusercontent.com/bluesky-social/bsky-docs/main/docs/advanced-guides/backfill.md",
    "headings": [
      "Overview",
      "Some things to keep in mind"
    ]
  },
  {
    "id": "bsky/advanced-guides/custom-schemas",
    "source": "bsky",
    "title": "Custom Schemas",
    "description": "The AT Protocol, and specifically Lexicon, provides a toolkit for creating decentralization social applications. Lexicon is meant to be a social coordination tool. It's an explicit way to announce the schema that some d…",
    "url": "https://docs.bsky.app/docs/advanced-guides/custom-schemas",
    "raw": "https://raw.githubusercontent.com/bluesky-social/bsky-docs/main/docs/advanced-guides/custom-schemas.mdx",
    "headings": [
      "Records",
      "APIs",
      "Sub-schemas"
    ]
  },
  {
    "id": "bsky/advanced-guides/entryway",
    "source": "bsky",
    "title": "PDS Entryway",
    "description": "Bluesky runs many PDSs. Each PDS runs as a completely separate service in the network with its own identity. They federate with the rest of the network in the exact same manner that a non-Bluesky PDS does. These PDSs ha…",
    "url": "https://docs.bsky.app/docs/advanced-guides/entryway",
    "raw": "https://raw.githubusercontent.com/bluesky-social/bsky-docs/main/docs/advanced-guides/entryway.md",
    "headings": [
      "Account Management",
      "Virtual PDS",
      "Engaging with Entryway as a developer"
    ]
  },
  {
    "id": "bsky/advanced-guides/federation-architecture",
    "source": "bsky",
    "title": "Federation Architecture",
    "description": "The AT Protocol is made up of a bunch of pieces that stack together. Federation means that anyone can run the parts that make up the AT Protocol themselves, such as their own server.",
    "url": "https://docs.bsky.app/docs/advanced-guides/federation-architecture",
    "raw": "https://raw.githubusercontent.com/bluesky-social/bsky-docs/main/docs/advanced-guides/federation-architecture.md",
    "headings": [
      "Personal Data Server (PDS)",
      "Relay",
      "App Views",
      "Self-Hosting"
    ]
  },
  {
    "id": "bsky/advanced-guides/firehose",
    "source": "bsky",
    "title": "Firehose",
    "description": "One of the core primitives of the AT Protocol that underlies Bluesky is the",
    "url": "https://docs.bsky.app/docs/advanced-guides/firehose",
    "raw": "https://raw.githubusercontent.com/bluesky-social/bsky-docs/main/docs/advanced-guides/firehose.mdx",
    "headings": []
  },
  {
    "id": "bsky/advanced-guides/intent-links",
    "source": "bsky",
    "title": "Action Intent Links",
    "description": "Authors, websites, and apps can use action intent links to implement \"Share on Bluesky\" buttons, or similar in-app actions. Logged-in users will be directed to the corresponding action view in the Bluesky app (mobile or…",
    "url": "https://docs.bsky.app/docs/advanced-guides/intent-links",
    "raw": "https://raw.githubusercontent.com/bluesky-social/bsky-docs/main/docs/advanced-guides/intent-links.md",
    "headings": [
      "Compose Post",
      "Button Styling"
    ]
  },
  {
    "id": "bsky/advanced-guides/moderation",
    "source": "bsky",
    "title": "Labels and moderation",
    "description": "Moderation in Bluesky consists of multiple, stackable systems, including:",
    "url": "https://docs.bsky.app/docs/advanced-guides/moderation",
    "raw": "https://raw.githubusercontent.com/bluesky-social/bsky-docs/main/docs/advanced-guides/moderation.md",
    "headings": [
      "Labels",
      "Label values",
      "Global label values",
      "Custom label values",
      "Label targets",
      "Label configuration",
      "Labelers",
      "Labeler declarations",
      "Labeler subscriptions",
      "Self-labels",
      "Reporting",
      "Official SDK",
      "Configuration",
      "Labeler management"
    ]
  },
  {
    "id": "bsky/advanced-guides/oauth-client",
    "source": "bsky",
    "title": "OAuth Client Implementation",
    "description": "This is a guide to implementing atproto OAuth clients \"The Hard Way.\" Optimistically, most developers will have an SDK available for their programming language which supports OAuth, and they can simply refer to SDK docu…",
    "url": "https://docs.bsky.app/docs/advanced-guides/oauth-client",
    "raw": "https://raw.githubusercontent.com/bluesky-social/bsky-docs/main/docs/advanced-guides/oauth-client.md",
    "headings": [
      "Types of Clients",
      "Components",
      "Client and Server Metadata",
      "PKCE",
      "PAR",
      "DPoP",
      "Confidential Client Authentication",
      "Token Management",
      "Hardened HTTP Client (SSRF)",
      "Authorization Flow",
      "Account or Server Identifier",
      "Authorization Request",
      "Callback and Access Token Request",
      "PDS Requests and Token Refresh"
    ]
  },
  {
    "id": "bsky/advanced-guides/oembed",
    "source": "bsky",
    "title": "oEmbed and Post Embed Widget",
    "description": "Bluesky posts can be embedded in other websites a couple different ways. For a non-technical guide on how to embed Bluesky posts on other websites, [read here](https://bsky.social/about/blog/post-embeds-guide).",
    "url": "https://docs.bsky.app/docs/advanced-guides/oembed",
    "raw": "https://raw.githubusercontent.com/bluesky-social/bsky-docs/main/docs/advanced-guides/oembed.md",
    "headings": [
      "oEmbed Endpoint"
    ]
  },
  {
    "id": "bsky/advanced-guides/post-richtext",
    "source": "bsky",
    "title": "Links, mentions, and rich text",
    "description": "Posts in Bluesky use *rich text* to handle links, mentions, and other kinds of decorated text.",
    "url": "https://docs.bsky.app/docs/advanced-guides/post-richtext",
    "raw": "https://raw.githubusercontent.com/bluesky-social/bsky-docs/main/docs/advanced-guides/post-richtext.md",
    "headings": [
      "Rich text facets",
      "Text encoding and indexing",
      "Producing facets"
    ]
  },
  {
    "id": "bsky/advanced-guides/posts",
    "source": "bsky",
    "title": "Posts",
    "description": "This is an in-depth dive into how creating a post works on Bluesky. We'll use Python below, without a SDK, so you can see how it works behind the scenes.",
    "url": "https://docs.bsky.app/docs/advanced-guides/posts",
    "raw": "https://raw.githubusercontent.com/bluesky-social/bsky-docs/main/docs/advanced-guides/posts.md",
    "headings": [
      "Post Record Structure",
      "Setting the language",
      "Mentions and links",
      "Replies, quote posts, and embeds",
      "Replies",
      "Quote posts",
      "Images embeds",
      "Website card embeds",
      "Putting it all together"
    ]
  },
  {
    "id": "bsky/advanced-guides/rate-limits",
    "source": "bsky",
    "title": "Rate Limits",
    "description": "Rate limits help service providers keep the network secure. For example, by limiting the number of requests a user or bot can make in a given time period, it prevents bad actors from brute-forcing certain requests and h…",
    "url": "https://docs.bsky.app/docs/advanced-guides/rate-limits",
    "raw": "https://raw.githubusercontent.com/bluesky-social/bsky-docs/main/docs/advanced-guides/rate-limits.md",
    "headings": [
      "Content Write Operations (per account)",
      "Hosted Account (PDS) Limits",
      "Bluesky AppView Limits",
      "Relay Limits",
      "Label Limits"
    ]
  },
  {
    "id": "bsky/advanced-guides/read-after-write",
    "source": "bsky",
    "title": "Read-After-Write",
    "description": "A user may take some action (such as updating their profile), rapidly refresh the view, and find that their recent change is not immediately reflected in the updated response.",
    "url": "https://docs.bsky.app/docs/advanced-guides/read-after-write",
    "raw": "https://raw.githubusercontent.com/bluesky-social/bsky-docs/main/docs/advanced-guides/read-after-write.md",
    "headings": [
      "Supported routes"
    ]
  },
  {
    "id": "bsky/advanced-guides/resolving-identities",
    "source": "bsky",
    "title": "Resolving Identities",
    "description": "Identities in the Bluesky network consist of multiple parts:",
    "url": "https://docs.bsky.app/docs/advanced-guides/resolving-identities",
    "raw": "https://raw.githubusercontent.com/bluesky-social/bsky-docs/main/docs/advanced-guides/resolving-identities.md",
    "headings": [
      "For Clients",
      "For Backend Services"
    ]
  },
  {
    "id": "bsky/advanced-guides/service-auth",
    "source": "bsky",
    "title": "Service Auth",
    "description": "There are currently two \"types\" of auth supported in the atproto network: client-server auth and service-to-service auth.",
    "url": "https://docs.bsky.app/docs/advanced-guides/service-auth",
    "raw": "https://raw.githubusercontent.com/bluesky-social/bsky-docs/main/docs/advanced-guides/service-auth.mdx",
    "headings": [
      "Usage"
    ]
  },
  {
    "id": "bsky/advanced-guides/timestamps",
    "source": "bsky",
    "title": "Timestamps",
    "description": "Bluesky is a distributed network, which means [clocks can skew](https://en.wikipedia.org/wiki/Clock_skew) and [time is relative](https://en.wikipedia.org/wiki/General_relativity). Furthermore, tricksters might lie about…",
    "url": "https://docs.bsky.app/docs/advanced-guides/timestamps",
    "raw": "https://raw.githubusercontent.com/bluesky-social/bsky-docs/main/docs/advanced-guides/timestamps.md",
    "headings": [
      "Recommendations",
      "Reject far-past and far-future timestamps",
      "Have a window of fuzziness",
      "Timestamps in the Bluesky application",
      "createdAt",
      "indexedAt",
      "sortAt",
      "Record Key TIDs",
      "Repository Commit Revision TIDs",
      "Firehose Event Timestamps"
    ]
  },
  {
    "id": "bsky/get-started",
    "source": "bsky",
    "title": "Get Started",
    "description": "Make your first post to the Bluesky app via the API in under 5 minutes.",
    "url": "https://docs.bsky.app/docs/get-started",
    "raw": "https://raw.githubusercontent.com/bluesky-social/bsky-docs/main/docs/get-started.mdx",
    "headings": [
      "Install the SDK",
      "Create a session",
      "Create a post",
      "Next Steps"
    ]
  },
  {
    "id": "bsky/starter-templates/bots",
    "source": "bsky",
    "title": "Bots",
    "description": "Bots are accounts on the network that post automatically. Popular ones include bots that post the magnitude of recent earthquakes, photos from an archive on a regular schedule, etc.",
    "url": "https://docs.bsky.app/docs/starter-templates/bots",
    "raw": "https://raw.githubusercontent.com/bluesky-social/bsky-docs/main/docs/starter-templates/bots.mdx",
    "headings": [
      "Starter Template",
      "Getting Started",
      "Create a Script",
      "Deploying Your Bot",
      "Labeling Your Bot",
      "Rate Limits & Respecting Other Users",
      "Session Management"
    ]
  },
  {
    "id": "bsky/starter-templates/clients",
    "source": "bsky",
    "title": "Client Apps",
    "description": "Bluesky is a public social network with completely open APIs, so anyone can build a client app and have access to the same data that the Bluesky app uses. In fact, the official Bluesky client uses the same APIs that a t…",
    "url": "https://docs.bsky.app/docs/starter-templates/clients",
    "raw": "https://raw.githubusercontent.com/bluesky-social/bsky-docs/main/docs/starter-templates/clients.mdx",
    "headings": [
      "Getting Started",
      "Setting up the API client"
    ]
  },
  {
    "id": "bsky/starter-templates/custom-feeds",
    "source": "bsky",
    "title": "Custom Feeds",
    "description": "Custom feeds, or feed generators, are services that provide custom algorithms to users through the AT Protocol. This allows users to choose their own timelines, whether it's an algorithmic For You page or a feed of enti…",
    "url": "https://docs.bsky.app/docs/starter-templates/custom-feeds",
    "raw": "https://raw.githubusercontent.com/bluesky-social/bsky-docs/main/docs/starter-templates/custom-feeds.mdx",
    "headings": [
      "Overview",
      "Starter Template",
      "Getting Started",
      "Deploying your feed",
      "Publishing your feed",
      "Running the Server",
      "Some Details"
    ]
  },
  {
    "id": "bsky/support/developer-guidelines",
    "source": "bsky",
    "title": "Bluesky Developer Guidelines",
    "description": "Developers who federate their apps or services on the AT Protocol must adhere to the Bluesky Developer Guidelines in order to communicate with Bluesky services:",
    "url": "https://docs.bsky.app/docs/support/developer-guidelines",
    "raw": "https://raw.githubusercontent.com/bluesky-social/bsky-docs/main/docs/support/developer-guidelines.md",
    "headings": []
  },
  {
    "id": "bsky/support/mailing-list",
    "source": "bsky",
    "title": "Developer Mailing List",
    "description": "To receive Bluesky developer updates in your inbox, subscribe to the developer mailing list.",
    "url": "https://docs.bsky.app/docs/support/mailing-list",
    "raw": "https://raw.githubusercontent.com/bluesky-social/bsky-docs/main/docs/support/mailing-list.mdx",
    "headings": []
  },
  {
    "id": "bsky/tutorials/blocking",
    "source": "bsky",
    "title": "Blocking users",
    "description": "Blocking a user prevents interaction and hides the user from the client experience. Blocked accounts will not be able to like, reply, mention, or follow you. Their posts, replies, and profile in search will also be hidd…",
    "url": "https://docs.bsky.app/docs/tutorials/blocking",
    "raw": "https://raw.githubusercontent.com/bluesky-social/bsky-docs/main/docs/tutorials/blocking.mdx",
    "headings": [
      "Unblocking a user"
    ]
  },
  {
    "id": "bsky/tutorials/creating-a-post",
    "source": "bsky",
    "title": "Creating a post",
    "description": "Bluesky posts are repository records with the [Lexicon type](https://github.com/bluesky-social/atproto/blob/main/lexicons/app/bsky/feed/post.json) `app.bsky.feed.post`.",
    "url": "https://docs.bsky.app/docs/tutorials/creating-a-post",
    "raw": "https://raw.githubusercontent.com/bluesky-social/bsky-docs/main/docs/tutorials/creating-a-post.mdx",
    "headings": [
      "Setting the language",
      "Mentions and Links",
      "Replies, quote posts, and embeds",
      "Replies",
      "Quote posts",
      "Images embeds",
      "Website card embeds"
    ]
  },
  {
    "id": "bsky/tutorials/custom-feeds",
    "source": "bsky",
    "title": "Custom feeds",
    "description": "Custom feeds are algorithmic feed generators. To users, this is their timeline. This tutorial will explain how to interact with a feed generator in the network.",
    "url": "https://docs.bsky.app/docs/tutorials/custom-feeds",
    "raw": "https://raw.githubusercontent.com/bluesky-social/bsky-docs/main/docs/tutorials/custom-feeds.mdx",
    "headings": [
      "Getting a feed generator's description",
      "Viewing a feed generator's posts",
      "Has the user liked a feedgen?",
      "Liking and unliking a feedgen"
    ]
  },
  {
    "id": "bsky/tutorials/editing-profiles",
    "source": "bsky",
    "title": "Editing profiles",
    "description": "An authenticated user can edit their profile, including updating their display",
    "url": "https://docs.bsky.app/docs/tutorials/editing-profiles",
    "raw": "https://raw.githubusercontent.com/bluesky-social/bsky-docs/main/docs/tutorials/editing-profiles.mdx",
    "headings": [
      "Updating profile avatar or banner"
    ]
  },
  {
    "id": "bsky/tutorials/following",
    "source": "bsky",
    "title": "Following and unfollowing",
    "description": "Following a user is as easy as calling `agent.follow` with the DID of the user you want to follow.",
    "url": "https://docs.bsky.app/docs/tutorials/following",
    "raw": "https://raw.githubusercontent.com/bluesky-social/bsky-docs/main/docs/tutorials/following.mdx",
    "headings": [
      "Following",
      "Unfollowing"
    ]
  },
  {
    "id": "bsky/tutorials/like-repost",
    "source": "bsky",
    "title": "Liking and reposting",
    "description": "Liking and reposting posts are a core feature of Bluesky. The [official atproto SDK](https://www.npmjs.com/package/@atproto/api) has dedicated methods for these actions.",
    "url": "https://docs.bsky.app/docs/tutorials/like-repost",
    "raw": "https://raw.githubusercontent.com/bluesky-social/bsky-docs/main/docs/tutorials/like-repost.mdx",
    "headings": [
      "Liking a post",
      "Unliking a post",
      "Reposting a post",
      "Un-reposting a post",
      "Quote reposting"
    ]
  },
  {
    "id": "bsky/tutorials/muting",
    "source": "bsky",
    "title": "Muting users",
    "description": "Muting a user hides their posts from your feeds. Mutes are private — like Bookmarks, they are stored on the [Bluesky AppView](/docs/advanced-guides/federation-architecture#app-views), rather than in your PDS. Muting a u…",
    "url": "https://docs.bsky.app/docs/tutorials/muting",
    "raw": "https://raw.githubusercontent.com/bluesky-social/bsky-docs/main/docs/tutorials/muting.mdx",
    "headings": [
      "Unmuting a user"
    ]
  },
  {
    "id": "bsky/tutorials/thread-gates",
    "source": "bsky",
    "title": "Thread gates",
    "description": "Thread gates set who can reply to a post.",
    "url": "https://docs.bsky.app/docs/tutorials/thread-gates",
    "raw": "https://raw.githubusercontent.com/bluesky-social/bsky-docs/main/docs/tutorials/thread-gates.mdx",
    "headings": [
      "Setting a thread gate"
    ]
  },
  {
    "id": "bsky/tutorials/user-lists",
    "source": "bsky",
    "title": "User lists",
    "description": "The **app.bsky.graph.list** record type declares the existence of a list.",
    "url": "https://docs.bsky.app/docs/tutorials/user-lists",
    "raw": "https://raw.githubusercontent.com/bluesky-social/bsky-docs/main/docs/tutorials/user-lists.mdx",
    "headings": [
      "List purpose",
      "Viewing a list",
      "Get created lists",
      "Get muted lists",
      "Get blocked lists",
      "Has a user muted or blocked a list?",
      "Mute/unmute a list",
      "Block/unblock a list",
      "Create a list",
      "Update a list's metadata",
      "Delete a list",
      "Add a user to a list",
      "Remove a user from a list"
    ]
  },
  {
    "id": "bsky/tutorials/video",
    "source": "bsky",
    "title": "Uploading Video",
    "description": "Video uploads differ slightly from image uploads, since they are typically much larger files and have a significantly long processing time.",
    "url": "https://docs.bsky.app/docs/tutorials/video",
    "raw": "https://raw.githubusercontent.com/bluesky-social/bsky-docs/main/docs/tutorials/video.mdx",
    "headings": [
      "Simple method",
      "Recommended method",
      "Aspect Ratios"
    ]
  },
  {
    "id": "bsky/tutorials/viewing-feeds",
    "source": "bsky",
    "title": "Viewing feeds",
    "description": "Feeds are lists of posts, paginated by cursors. Bluesky has a few types of feeds:",
    "url": "https://docs.bsky.app/docs/tutorials/viewing-feeds",
    "raw": "https://raw.githubusercontent.com/bluesky-social/bsky-docs/main/docs/tutorials/viewing-feeds.mdx",
    "headings": [
      "Viewing a user's timeline",
      "Feed generators",
      "Author feeds"
    ]
  },
  {
    "id": "bsky/tutorials/viewing-profiles",
    "source": "bsky",
    "title": "Viewing profiles",
    "description": "A profile is typically made up of a user's biographical information, and their",
    "url": "https://docs.bsky.app/docs/tutorials/viewing-profiles",
    "raw": "https://raw.githubusercontent.com/bluesky-social/bsky-docs/main/docs/tutorials/viewing-profiles.mdx",
    "headings": [
      "Fetching a user's profile info",
      "Fetching multiple profiles at once"
    ]
  },
  {
    "id": "bsky/tutorials/viewing-threads",
    "source": "bsky",
    "title": "Viewing threads",
    "description": "A _thread_ refers to a post, its replies (descendants), and its parents",
    "url": "https://docs.bsky.app/docs/tutorials/viewing-threads",
    "raw": "https://raw.githubusercontent.com/bluesky-social/bsky-docs/main/docs/tutorials/viewing-threads.mdx",
    "headings": [
      "Data shape",
      "The depth and parentHeight parameters",
      "Handling blocks, takedowns, and not found"
    ]
  },
  {
    "id": "guides/about-oauth",
    "source": "atproto",
    "title": "About OAuth",
    "description": "OAuth implementation patterns for atproto applications",
    "url": "https://atproto.com/guides/about-oauth",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/about-oauth/en.mdx",
    "headings": [
      "SDK Libraries",
      "TypeScript",
      "Go",
      "Atproto OAuth Example Apps",
      "How the OAuth flow works",
      "Types of App",
      "Further Reading and Resources"
    ]
  },
  {
    "id": "guides/account-lifecycle",
    "source": "atproto",
    "title": "Accounts and deletions",
    "description": "How account lifecycles and deletions work in AT Protocol",
    "url": "https://atproto.com/guides/account-lifecycle",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/account-lifecycle/en.mdx",
    "headings": [
      "Account lifecycles",
      "New Account Creation",
      "Account Migration",
      "Account Deletion",
      "Account Deactivation",
      "Account Reactivation",
      "Further Reading and Resources"
    ]
  },
  {
    "id": "guides/account-management",
    "source": "atproto",
    "title": "Account Management",
    "description": "How to manage your Atmosphere account",
    "url": "https://atproto.com/guides/account-management",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/account-management/en.mdx",
    "headings": [
      "Account Creation",
      "Account Management",
      "Account Migration"
    ]
  },
  {
    "id": "guides/account-migration",
    "source": "atproto",
    "title": "Account Migration",
    "description": "Migrating an account to a new PDS",
    "url": "https://atproto.com/guides/account-migration",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/account-migration/en.mdx",
    "headings": [
      "Creating a New Account",
      "Migrating Data",
      "Repositories",
      "Blobs",
      "Preferences",
      "Updating Identity",
      "Finalizing Account Status"
    ]
  },
  {
    "id": "guides/account-recovery",
    "source": "atproto",
    "title": "Account Recovery",
    "description": "Self-custodying your AT Protocol identity with rotation keys",
    "url": "https://atproto.com/guides/account-recovery",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/account-recovery/en.mdx",
    "headings": [
      "Do You Need This?",
      "How Identity Works",
      "Rotation Keys",
      "Pre-registering a Key",
      "Verifying Your Setup",
      "Using Your Key for Recovery",
      "Further Reading"
    ]
  },
  {
    "id": "guides/auth",
    "source": "atproto",
    "title": "Auth",
    "description": "Auth for atproto application developers",
    "url": "https://atproto.com/guides/auth",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/auth/en.mdx",
    "headings": [
      "Getting Started",
      "About authorization",
      "What is OAuth?",
      "Further Reading and Resources"
    ]
  },
  {
    "id": "guides/backfilling",
    "source": "atproto",
    "title": "Backfilling",
    "description": "Replicating the network",
    "url": "https://atproto.com/guides/backfilling",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/backfilling/en.mdx",
    "headings": [
      "When to backfill",
      "Using tap",
      "How backfilling works",
      "Further Reading and Resources"
    ]
  },
  {
    "id": "guides/blob-lifecycle",
    "source": "atproto",
    "title": "Blob Lifecycle",
    "description": "How blobs are uploaded, referenced, and deleted",
    "url": "https://atproto.com/guides/blob-lifecycle",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/blob-lifecycle/en.mdx",
    "headings": [
      "Uploading blobs",
      "Garbage collecting",
      "Referencing blobs",
      "Deleting blobs",
      "Web accessibility",
      "Related resources"
    ]
  },
  {
    "id": "guides/blob-security",
    "source": "atproto",
    "title": "Blob Security",
    "description": "Security considerations when serving blobs",
    "url": "https://atproto.com/guides/blob-security",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/blob-security/en.mdx",
    "headings": [
      "HTTP requests",
      "Metadata",
      "Adversarial use",
      "Related resources"
    ]
  },
  {
    "id": "guides/bot-tutorial",
    "source": "atproto",
    "title": "Build an Agent",
    "description": "Create a bot that automatically posts on Bluesky",
    "url": "https://atproto.com/guides/bot-tutorial",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/bot-tutorial/en.mdx",
    "headings": [
      "Prerequisites",
      "Part 1: Lexicons",
      "Part 2: Create a Bot",
      "Part 3: Label as a Bot",
      "Part 4: Run the Bot",
      "Part 5: From Bot to Agent",
      "Conclusion"
    ]
  },
  {
    "id": "guides/creating-a-labeler",
    "source": "atproto",
    "title": "Creating a Labeler",
    "description": "Run your own modular moderation service",
    "url": "https://atproto.com/guides/creating-a-labeler",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/creating-a-labeler/en.mdx",
    "headings": [
      "Declaring a labeler",
      "Updating your labeler",
      "Ozone",
      "Further Reading and Resources"
    ]
  },
  {
    "id": "guides/custom-feed-tutorial",
    "source": "atproto",
    "title": "Write a Custom Feed",
    "description": "Host an algorithm that\\",
    "url": "https://atproto.com/guides/custom-feed-tutorial",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/custom-feed-tutorial/en.mdx",
    "headings": [
      "Prerequisites",
      "Part 1: Lexicons and Tap",
      "Part 2: Feed Structure",
      "Part 3: Consuming the Firehose",
      "Part 4: Serving the Feed",
      "Part 5: Running the Server",
      "Conclusion"
    ]
  },
  {
    "id": "guides/data-repos",
    "source": "atproto",
    "title": "Personal Data Repositories",
    "description": "A guide to the AT Protocol repo structure.",
    "url": "https://atproto.com/guides/data-repos",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/data-repos/en.mdx",
    "headings": [
      "Data Layout",
      "Identifier Types"
    ]
  },
  {
    "id": "guides/data-validation",
    "source": "atproto",
    "title": "guides/data-validation",
    "description": "",
    "url": "https://atproto.com/guides/data-validation",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/data-validation/en.mdx",
    "headings": [
      "Recommended Data Limits",
      "Validation Without Schema"
    ]
  },
  {
    "id": "guides/faq",
    "source": "atproto",
    "title": "FAQ",
    "description": "Frequently Asked Questions about AT Protocol.",
    "url": "https://atproto.com/guides/faq",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/faq/en.mdx",
    "headings": [
      "Is the AT Protocol a blockchain?",
      "Why not use ActivityPub?",
      "Why create Lexicon instead of using JSON-LD or RDF?",
      "What is \"XRPC,\" and why not use ___?"
    ]
  },
  {
    "id": "guides/feeds",
    "source": "atproto",
    "title": "Feeds",
    "description": "Creating and consuming custom feed generators",
    "url": "https://atproto.com/guides/feeds",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/feeds/en.mdx",
    "headings": [
      "Custom Feeds",
      "Feed Generator Templates",
      "Implementing Feeds",
      "Language Handling",
      "Feed Feedback",
      "Example Feeds",
      "Further Reading and Resources"
    ]
  },
  {
    "id": "guides/glossary",
    "source": "atproto",
    "title": "Glossary of terms",
    "description": "A collection of terminology used in the AT Protocol and their definitions.",
    "url": "https://atproto.com/guides/glossary",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/glossary/en.mdx",
    "headings": [
      "Atmosphere",
      "AT Protocol",
      "PDS (Personal Data Server)",
      "AppView",
      "Relay",
      "Lexicon",
      "Data Repo",
      "Collection",
      "Record",
      "Blob",
      "Label",
      "Handle",
      "DID (Decentralized ID)",
      "NSID (Namespaced ID)"
    ]
  },
  {
    "id": "guides/go-oauth-cli-tutorial",
    "source": "atproto",
    "title": "OAuth with Go Tutorial",
    "description": "Authenticate with atproto OAuth from a Go app",
    "url": "https://atproto.com/guides/go-oauth-cli-tutorial",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/go-oauth-cli-tutorial/en.mdx",
    "headings": [
      "Prerequisites",
      "Part 1: Project Setup",
      "Part 2: Build the OAuth Client",
      "Part 3: Login Flow",
      "Part 4: Use the Session",
      "Part 5: Helper Functions",
      "Part 6: Run It",
      "Conclusion"
    ]
  },
  {
    "id": "guides/going-to-production",
    "source": "atproto",
    "title": "Going to production",
    "description": "Improving your Atmosphere stack deployment for production use at scale",
    "url": "https://atproto.com/guides/going-to-production",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/going-to-production/en.mdx",
    "headings": [
      "PDS",
      "Hardening",
      "Domain names",
      "Backups and Recovery",
      "PLC key management",
      "Object storage",
      "Rate limits",
      "Moderation",
      "Preventing spam"
    ]
  },
  {
    "id": "guides/identity",
    "source": "atproto",
    "title": "Identity",
    "description": "How the AT Protocol handles user identity.",
    "url": "https://atproto.com/guides/identity",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/identity/en.mdx",
    "headings": [
      "Identifiers",
      "DID Methods",
      "Handle Resolution",
      "Example: Hosting service",
      "Example: Self-hosted"
    ]
  },
  {
    "id": "guides/images-and-video",
    "source": "atproto",
    "title": "Images and Video",
    "description": "Working with image and video blobs",
    "url": "https://atproto.com/guides/images-and-video",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/images-and-video/en.mdx",
    "headings": [
      "Using blobs",
      "Blob objects",
      "Further Reading and Resources"
    ]
  },
  {
    "id": "guides/installing-lexicons",
    "source": "atproto",
    "title": "Developing with Lexicons",
    "description": "Using Lexicons in your dev environment",
    "url": "https://atproto.com/guides/installing-lexicons",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/installing-lexicons/en.mdx",
    "headings": [
      "Installing Lexicons with lex",
      "TypeScript",
      "XRPC Methods",
      "Using the .internal TLD",
      "Further Reading and Resources"
    ]
  },
  {
    "id": "guides/labels",
    "source": "atproto",
    "title": "Labels",
    "description": "All about moderation labels",
    "url": "https://atproto.com/guides/labels",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/labels/en.mdx",
    "headings": [
      "About labels",
      "Label values",
      "Global label values",
      "Custom label values",
      "Label configuration",
      "Further Reading and Resources"
    ]
  },
  {
    "id": "guides/labels-tutorial",
    "source": "atproto",
    "title": "Add Labels to Your App",
    "description": "Wire your Statusphere app to an Ozone labeler service to display and create labels.",
    "url": "https://atproto.com/guides/labels-tutorial",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/labels-tutorial/en.mdx",
    "headings": [
      "Prerequisites",
      "Part 1: Wiring the Labeler Into Your App",
      "Part 2: Querying Labels",
      "Part 3: Capturing Record CIDs",
      "Part 4: Reporting Statuses",
      "Part 5: Displaying Labels in the Feed",
      "Conclusion"
    ]
  },
  {
    "id": "guides/lexicon",
    "source": "atproto",
    "title": "Lexicons",
    "description": "A schema-driven interoperability framework",
    "url": "https://atproto.com/guides/lexicon",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/lexicon/en.mdx",
    "headings": [
      "About lexicons",
      "HTTP API methods",
      "Record types",
      "Versioning",
      "Further Reading and Resources"
    ]
  },
  {
    "id": "guides/lexicon-style-guide",
    "source": "atproto",
    "title": "Lexicon Style Guide",
    "description": "A style guide for creating new atproto Lexicons",
    "url": "https://atproto.com/guides/lexicon-style-guide",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/lexicon-style-guide/en.mdx",
    "headings": [
      "Overview",
      "Naming conventions",
      "Documentation",
      "Other guidelines",
      "Lexicon evolution",
      "Design Patterns"
    ]
  },
  {
    "id": "guides/moderation",
    "source": "atproto",
    "title": "Moderation",
    "description": "Moderation in the Atmosphere",
    "url": "https://atproto.com/guides/moderation",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/moderation/en.mdx",
    "headings": [
      "About moderation",
      "Algorithmic moderation",
      "Further Reading and Resources"
    ]
  },
  {
    "id": "guides/oauth-cli-tutorial",
    "source": "atproto",
    "title": "OAuth with Node Tutorial",
    "description": "Authenticate with atproto OAuth from Node.js",
    "url": "https://atproto.com/guides/oauth-cli-tutorial",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/oauth-cli-tutorial/en.mdx",
    "headings": [
      "Prerequisites",
      "Part 1: Project Setup",
      "Part 2: Build the OAuth Client",
      "Part 3: Login Flow",
      "Part 4: Use the Session",
      "Part 5: Run It",
      "Conclusion"
    ]
  },
  {
    "id": "guides/oauth-patterns",
    "source": "atproto",
    "title": "OAuth Patterns",
    "description": "Advanced OAuth implementation patterns for atproto applications",
    "url": "https://atproto.com/guides/oauth-patterns",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/oauth-patterns/en.mdx",
    "headings": [
      "How is OAuth Different in AT Protocol?",
      "Understanding DPoP",
      "PKCE and PAR",
      "Token Refresh",
      "Session Storage",
      "Progressive scope requests",
      "Selecting scopes before authorization",
      "Upgrading scopes for an existing session",
      "Further Reading and Resources"
    ]
  },
  {
    "id": "guides/oauth-tutorial",
    "source": "atproto",
    "title": "OAuth with NextJS Tutorial",
    "description": "Build a Next.js app supporting OAuth with atproto identity.",
    "url": "https://atproto.com/guides/oauth-tutorial",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/oauth-tutorial/en.mdx",
    "headings": [
      "Prerequisites",
      "Part 1: Project Setup",
      "Part 2: Implementing OAuth",
      "Part 3: Adding Database Persistence",
      "Part 4: Deploying to Production",
      "Conclusion"
    ]
  },
  {
    "id": "guides/overview",
    "source": "atproto",
    "title": "Protocol Overview",
    "description": "An introduction to the AT Protocol.",
    "url": "https://atproto.com/guides/overview",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/overview/en.mdx",
    "headings": [
      "Identity",
      "Data Repositories",
      "Network Architecture",
      "Interoperation",
      "Achieving Scale",
      "Algorithmic choice",
      "Account portability",
      "Speech, reach, and moderation",
      "Specifications"
    ]
  },
  {
    "id": "guides/permission-requests",
    "source": "atproto",
    "title": "Permission Requests",
    "description": "A permissions guide for app developers and Lexicon designers",
    "url": "https://atproto.com/guides/permission-requests",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/permission-requests/en.mdx",
    "headings": [
      "Overview",
      "Requesting permissions",
      "Permission types",
      "Permission sets",
      "Clients",
      "Rolling out changes",
      "OAuth flow examples",
      "Further Reading and Resources"
    ]
  },
  {
    "id": "guides/permission-sets",
    "source": "atproto",
    "title": "Permission Sets",
    "description": "OAuth permission scopes and sets",
    "url": "https://atproto.com/guides/permission-sets",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/permission-sets/en.mdx",
    "headings": [
      "Understanding Permission Sets",
      "Quick start",
      "Minimal permissions",
      "Permission Set design",
      "Progressive scope requests",
      "Further Reading and Resources"
    ]
  },
  {
    "id": "guides/publishing-lexicons",
    "source": "atproto",
    "title": "Publishing Lexicons",
    "description": "Sharing your lexicons with the world",
    "url": "https://atproto.com/guides/publishing-lexicons",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/publishing-lexicons/en.mdx",
    "headings": [
      "Lexicon lifecycle",
      "Using goat",
      "Further Reading and Resources"
    ]
  },
  {
    "id": "guides/reading-data",
    "source": "atproto",
    "title": "Reading Data",
    "description": "Read AT Protocol Records",
    "url": "https://atproto.com/guides/reading-data",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/reading-data/en.mdx",
    "headings": [
      "Listing Records",
      "Getting Records",
      "DID Resolution",
      "Unauthenticated Reads",
      "Further Reading and Resources"
    ]
  },
  {
    "id": "guides/reads-and-writes",
    "source": "atproto",
    "title": "Reads and Writes",
    "description": "Read and Write from the Atmosphere",
    "url": "https://atproto.com/guides/reads-and-writes",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/reads-and-writes/en.mdx",
    "headings": [
      "AT Records",
      "Prerequisites",
      "API Methods",
      "Further Reading and Resources"
    ]
  },
  {
    "id": "guides/scope-builder",
    "source": "atproto",
    "title": "Scope Builder",
    "description": "Compose an OAuth scope string for your app",
    "url": "https://atproto.com/guides/scope-builder",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/scope-builder/en.mdx",
    "headings": [
      "Further Reading and Resources"
    ]
  },
  {
    "id": "guides/sdk-auth",
    "source": "atproto",
    "title": "SDK authentication",
    "description": "Authenticating with the SDKs",
    "url": "https://atproto.com/guides/sdk-auth",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/sdk-auth/en.mdx",
    "headings": [
      "Password Authentication",
      "Client Sessions",
      "API Tokens",
      "Further Reading and Resources"
    ]
  },
  {
    "id": "guides/self-hosting",
    "source": "atproto",
    "title": "Self-hosting",
    "description": "Resources for self-hosting various components of the Atmosphere stack",
    "url": "https://atproto.com/guides/self-hosting",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/self-hosting/en.mdx",
    "headings": [
      "PDS",
      "Relays",
      "Tap",
      "AppViews",
      "Ozone",
      "Deploy Recipes"
    ]
  },
  {
    "id": "guides/social-graph",
    "source": "atproto",
    "title": "Social graph",
    "description": "Working with AT Protocol Social Graphs",
    "url": "https://atproto.com/guides/social-graph",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/social-graph/en.mdx",
    "headings": [
      "Querying social graphs",
      "Backlinks",
      "Reusing Lexicons",
      "Further Reading and Resources"
    ]
  },
  {
    "id": "guides/statusphere-tutorial",
    "source": "atproto",
    "title": "Create a Social App",
    "description": "Build an app that lets you broadcast and receive status updates using AT Record Lexicons.",
    "url": "https://atproto.com/guides/statusphere-tutorial",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/statusphere-tutorial/en.mdx",
    "headings": [
      "Prerequisites",
      "Part 1: Lexicons",
      "Part 2: Database Schema",
      "Part 3: Status Submission",
      "Part 4: Realtime Sync with Tap",
      "Part 5: Displaying Handles and Feeds",
      "Conclusion"
    ]
  },
  {
    "id": "guides/streaming-data",
    "source": "atproto",
    "title": "Streaming Data",
    "description": "Working with the Firehose and Jetstream",
    "url": "https://atproto.com/guides/streaming-data",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/streaming-data/en.mdx",
    "headings": [
      "Streaming data",
      "Firehose",
      "Jetstream",
      "Further Reading and Resources"
    ]
  },
  {
    "id": "guides/subscriptions",
    "source": "atproto",
    "title": "Subscriptions",
    "description": "Subscribing to a labeler service",
    "url": "https://atproto.com/guides/subscriptions",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/subscriptions/en.mdx",
    "headings": [
      "Labeler Subscriptions",
      "Use labels in your app",
      "Reporting",
      "Further Reading and Resources"
    ]
  },
  {
    "id": "guides/sync",
    "source": "atproto",
    "title": "Sync",
    "description": "Synchronizing AT Protocol data",
    "url": "https://atproto.com/guides/sync",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/sync/en.mdx",
    "headings": [
      "Handles and DIDs",
      "Data Repositories",
      "PDS",
      "Further Reading and Resources"
    ]
  },
  {
    "id": "guides/the-at-stack",
    "source": "atproto",
    "title": "The AT Stack",
    "description": "Components of the AT Protocol Stack",
    "url": "https://atproto.com/guides/the-at-stack",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/the-at-stack/en.mdx",
    "headings": [
      "The Authenticated Transfer Protocol",
      "Decentralized Architecture",
      "PDS",
      "Relays",
      "Tap",
      "App Views",
      "DID PLC",
      "Feeds",
      "Osprey and Ozone",
      "Tools and SDKs"
    ]
  },
  {
    "id": "guides/tutorials",
    "source": "atproto",
    "title": "Tutorials",
    "description": "AT Protocol Tutorials",
    "url": "https://atproto.com/guides/tutorials",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/tutorials/en.mdx",
    "headings": [
      "Build-a-Bot",
      "Custom Feed Algorithms",
      "OAuth with Go",
      "OAuth with Node.js",
      "OAuth with NextJS",
      "Statusphere Example App",
      "Add Labels to Your App"
    ]
  },
  {
    "id": "guides/understanding-atproto",
    "source": "atproto",
    "title": "Understanding Atproto",
    "description": "A closer look into how it all works",
    "url": "https://atproto.com/guides/understanding-atproto",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/understanding-atproto/en.mdx",
    "headings": [
      "TL;DR",
      "Core primitives",
      "Data models",
      "The stack",
      "Making it happen",
      "Deeper reads"
    ]
  },
  {
    "id": "guides/using-ozone",
    "source": "atproto",
    "title": "Using Ozone",
    "description": "Working with the Ozone moderation interface",
    "url": "https://atproto.com/guides/using-ozone",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/using-ozone/en.mdx",
    "headings": [
      "Getting started",
      "Installing Ozone",
      "Configuring Ozone",
      "Submitting and managing reports",
      "Next steps",
      "Further Reading and Resources"
    ]
  },
  {
    "id": "guides/video-handling",
    "source": "atproto",
    "title": "Video Handling",
    "description": "Handling video uploads and processing",
    "url": "https://atproto.com/guides/video-handling",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/video-handling/en.mdx",
    "headings": [
      "Video uploads",
      "Aspect ratios",
      "Transcoding",
      "Further Reading and Resources"
    ]
  },
  {
    "id": "guides/writing-data",
    "source": "atproto",
    "title": "Writing Data",
    "description": "Write AT Protocol Records",
    "url": "https://atproto.com/guides/writing-data",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/guides/writing-data/en.mdx",
    "headings": [
      "Writing Data",
      "Read-after-Write",
      "Updating Records",
      "Deleting Records",
      "Further Reading and Resources"
    ]
  },
  {
    "id": "specs/account",
    "source": "atproto",
    "title": "Accounts",
    "description": "Account Hosting and Lifecycle",
    "url": "https://atproto.com/specs/account",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/specs/account/en.mdx",
    "headings": [
      "Hosting Status",
      "Hosting Status Propagation",
      "Content Deletion",
      "PDS Account Migration",
      "Usage and Implementation Guidelines",
      "Security Considerations",
      "Future Work"
    ]
  },
  {
    "id": "specs/at-uri-scheme",
    "source": "atproto",
    "title": "AT URI scheme (at://)",
    "description": "A URI scheme for addressing atproto repository data.",
    "url": "https://atproto.com/specs/at-uri-scheme",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/specs/at-uri-scheme/en.mdx",
    "headings": [
      "Structure",
      "Generic URI Compliance",
      "Full AT URI Syntax",
      "Restricted AT URI Syntax",
      "Normalization",
      "Examples",
      "Usage and Implementation Guidelines",
      "Possible Future Changes"
    ]
  },
  {
    "id": "specs/atp",
    "source": "atproto",
    "title": "AT Protocol",
    "description": "Specification for the Authenticated Transfer Protocol (AT Protocol)",
    "url": "https://atproto.com/specs/atp",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/specs/atp/en.mdx",
    "headings": [
      "Protocol Structure",
      "Protocol Extension and Applications",
      "What is Missing?"
    ]
  },
  {
    "id": "specs/blob",
    "source": "atproto",
    "title": "Blobs",
    "description": "Media files referenced by records",
    "url": "https://atproto.com/specs/blob",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/specs/blob/en.mdx",
    "headings": [
      "Blob Metadata",
      "Blob Lifecycle",
      "Usage and Implementation Guidelines",
      "Security Considerations",
      "Possible Future Changes"
    ]
  },
  {
    "id": "specs/cryptography",
    "source": "atproto",
    "title": "Cryptography",
    "description": "Cryptographic systems, curves, and key types used in AT Protocol",
    "url": "https://atproto.com/specs/cryptography",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/specs/cryptography/en.mdx",
    "headings": [
      "ECDSA Signature Malleability",
      "Public Key Encoding",
      "Encoded Examples",
      "Usage and Implementation Guidelines",
      "Possible Future Changes"
    ]
  },
  {
    "id": "specs/data-model",
    "source": "atproto",
    "title": "Data Model",
    "description": "Consistent data encoding for records and messages.",
    "url": "https://atproto.com/specs/data-model",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/specs/data-model/en.mdx",
    "headings": [
      "Relationship With DASL and IPLD",
      "Data Types",
      "Nullable and False-y",
      "Why No Floats?",
      "blob Type",
      "JSON Representation",
      "link",
      "bytes",
      "Link and CID Formats",
      "Usage and Implementation Guidelines",
      "Security and Privacy Considerations",
      "Possible Future Changes"
    ]
  },
  {
    "id": "specs/did",
    "source": "atproto",
    "title": "DID",
    "description": "Persistent decentralized identifiers (as used in atproto)",
    "url": "https://atproto.com/specs/did",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/specs/did/en.mdx",
    "headings": [
      "Blessed DID Methods",
      "did:web in AT Protocol",
      "DID Identifier Syntax",
      "Examples",
      "DID Documents",
      "Representation of Public Keys",
      "Legacy Representation",
      "Usage and Implementation Guidelines",
      "Possible Future Changes"
    ]
  },
  {
    "id": "specs/event-stream",
    "source": "atproto",
    "title": "Event Stream",
    "description": "Network wire protocol for subscribing to a stream of Lexicon objects",
    "url": "https://atproto.com/specs/event-stream",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/specs/event-stream/en.mdx",
    "headings": [
      "Streaming Wire Protocol (v0)",
      "Connection",
      "Framing",
      "Sequence Numbers",
      "Usage and Implementation Guidelines",
      "Security and Privacy Considerations",
      "Possible Future Changes"
    ]
  },
  {
    "id": "specs/handle",
    "source": "atproto",
    "title": "Handle",
    "description": "A specification for human-friendly account identifiers.",
    "url": "https://atproto.com/specs/handle",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/specs/handle/en.mdx",
    "headings": [
      "Handle Identifier Syntax",
      "Additional Non-Syntax Restrictions",
      "Identifier Examples",
      "Handle Resolution",
      "DNS TXT Method",
      "HTTPS well-known Method",
      "Invalid Handles",
      "Resolution Best Practices",
      "Usage and Implementation Guidelines",
      "Possible Future Changes"
    ]
  },
  {
    "id": "specs/label",
    "source": "atproto",
    "title": "Labels",
    "description": "Self-authenticating string annotations on accounts or content for moderation and other purposes.",
    "url": "https://atproto.com/specs/label",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/specs/label/en.mdx",
    "headings": [
      "Schema and Data Model",
      "Value",
      "Recommended String Syntax",
      "Label Lifecycle: Negation and Expiration",
      "Signatures",
      "Signature Lifecycle",
      "Self-Labels in Records",
      "Labeler Service Identity",
      "Label Distribution Endpoints",
      "Labeler HTTP Headers",
      "Security Considerations",
      "Usage and Implementation Guidelines",
      "Possible Future Changes"
    ]
  },
  {
    "id": "specs/lexicon",
    "source": "atproto",
    "title": "Lexicon",
    "description": "A schema definition language.",
    "url": "https://atproto.com/specs/lexicon",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/specs/lexicon/en.mdx",
    "headings": [
      "Overview of Types",
      "Lexicon Files",
      "Primary Type Definitions",
      "Record",
      "Query and Procedure (HTTP API)",
      "Subscription (Event Stream)",
      "Permission Set",
      "Field Type Definitions",
      "boolean",
      "integer",
      "string",
      "bytes",
      "cid-link",
      "array"
    ]
  },
  {
    "id": "specs/nsid",
    "source": "atproto",
    "title": "Namespaced Identifiers (NSIDs)",
    "description": "A specification for global semantic IDs.",
    "url": "https://atproto.com/specs/nsid",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/specs/nsid/en.mdx",
    "headings": [
      "NSID Syntax",
      "NSID Syntax Variations",
      "Examples",
      "Usage and Implementation Guidelines",
      "Possible Future Changes"
    ]
  },
  {
    "id": "specs/oauth",
    "source": "atproto",
    "title": "OAuth",
    "description": "OAuth for Client/Server Authentication and Authorization",
    "url": "https://atproto.com/specs/oauth",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/specs/oauth/en.mdx",
    "headings": [
      "Clients",
      "Types of Clients",
      "Client ID Metadata Document",
      "Localhost Client Development",
      "Identity Authentication",
      "Authorization Scopes",
      "Transitional Scopes",
      "Authorization Requests",
      "Request Fields",
      "Proof Key for Code Exchange (PKCE)",
      "Pushed Authorization Requests (PAR)",
      "Confidential Client Authentication",
      "Tokens and Session Lifetime",
      "Demonstrating Proof of Possession (DPoP)"
    ]
  },
  {
    "id": "specs/permission",
    "source": "atproto",
    "title": "specs/permission",
    "description": "",
    "url": "https://atproto.com/specs/permission",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/specs/permission/en.mdx",
    "headings": [
      "Resource Types",
      "repo",
      "rpc",
      "blob",
      "account",
      "identity",
      "Scope String Syntax",
      "Permission Sets",
      "Namespace Authority",
      "Resolution and Caching",
      "Usage and Implementation Guidelines",
      "Possible Future Changes"
    ]
  },
  {
    "id": "specs/record-key",
    "source": "atproto",
    "title": "Record Key",
    "description": "Identifier for individual records in a collection",
    "url": "https://atproto.com/specs/record-key",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/specs/record-key/en.mdx",
    "headings": [
      "Record Key Type: tid",
      "Record Key Type: nsid",
      "Record Key Type: literal:<value>",
      "Record Key Type: any",
      "Record Key Syntax",
      "Examples",
      "Usage and Implementation Guidelines",
      "Possible Future Changes"
    ]
  },
  {
    "id": "specs/repository",
    "source": "atproto",
    "title": "Repository",
    "description": "Self-certifying storage for public account content",
    "url": "https://atproto.com/specs/repository",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/specs/repository/en.mdx",
    "headings": [
      "Repository Data Structure",
      "Repository Paths",
      "Commit Objects",
      "MST Structure",
      "CID Formats",
      "CAR File Serialization",
      "Streamable CAR Block Ordering",
      "Repository Diffs",
      "Security Considerations",
      "Possible Future Changes"
    ]
  },
  {
    "id": "specs/sync",
    "source": "atproto",
    "title": "Sync",
    "description": "Firehose and other data synchronization mechanisms.",
    "url": "https://atproto.com/specs/sync",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/specs/sync/en.mdx",
    "headings": [
      "Repository Revisions",
      "Repository Exports",
      "Repository Event Stream",
      "identity Events",
      "account Events",
      "commit Events",
      "sync Events",
      "Reliable Repository Synchronization",
      "Message Validation Checklist",
      "Record-Level Synchronization",
      "Usage and Implementation Guidelines",
      "Security Concerns",
      "Future Work"
    ]
  },
  {
    "id": "specs/tid",
    "source": "atproto",
    "title": "Timestamp Identifiers (TIDs)",
    "description": "A compact timestamp-based identifier for revisions and records.",
    "url": "https://atproto.com/specs/tid",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/specs/tid/en.mdx",
    "headings": [
      "TID Structure",
      "TID Syntax",
      "Examples"
    ]
  },
  {
    "id": "specs/xrpc",
    "source": "atproto",
    "title": "HTTP API (XRPC)",
    "description": "Cross-system queries and procedures over HTTP",
    "url": "https://atproto.com/specs/xrpc",
    "raw": "https://raw.githubusercontent.com/bluesky-social/atproto-website/main/src/app/%5Blocale%5D/specs/xrpc/en.mdx",
    "headings": [
      "Lexicon HTTP Endpoints",
      "Error Responses",
      "Blob Upload and Download",
      "Cursors and Pagination",
      "Authentication",
      "App Passwords",
      "Admin Token (Temporary Specification)",
      "Inter-Service Authentication (JWT)",
      "Service Proxying",
      "Summary of HTTP Headers",
      "Summary of HTTP Status Codes",
      "Usage and Implementation Guidelines",
      "Security and Privacy Considerations",
      "Possible Future Changes"
    ]
  }
];
