import { test } from 'node:test';
import assert from 'node:assert/strict';
import { existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { buildLlmsTxt } from '@/lib/llmsTxt';
import { API_ERROR_CODES, DOCUMENTED_API_PATHS } from '@/lib/openapi';

const BASE = 'https://example.test';
const txt = buildLlmsTxt(BASE);

test('follows the llmstxt.org shape: H1, blockquote summary, H2 sections', () => {
  const lines = txt.split('\n');
  assert.equal(lines[0], '# aturi.to');
  assert.ok(lines.some(l => l.startsWith('> ')), 'no blockquote summary');
  assert.ok(txt.split('\n').filter(l => l.startsWith('## ')).length >= 3);
  assert.equal(txt.match(/^# /gm)?.length, 1, 'exactly one H1');
});

test('answers "when should an agent reach for this?"', () => {
  assert.ok(txt.includes('## When to use this'));
  // Generic marketing copy does not read as dispatch guidance; the section has
  // to name the jobs and, just as usefully, the ones it is wrong for.
  assert.match(txt, /Do \*\*not\*\* reach for aturi\.to/);
});

test('names every operation an agent can call', () => {
  for (const id of ['resolveAtmosphereLink', 'listWaypoints', 'readAtTags', 'getPostOembed']) {
    assert.ok(txt.includes(id), `${id} is not mentioned`);
  }
});

test('points at the machine-readable entry points', () => {
  for (const path of ['/openapi.json', '/docs.md']) {
    assert.ok(txt.includes(`${BASE}${path}`), `${path} is not linked`);
  }
});

test('documents every public endpoint', () => {
  for (const path of DOCUMENTED_API_PATHS) {
    assert.ok(txt.includes(path), `${path} is missing from llms.txt`);
  }
});

test('lists the error codes an agent has to branch on', () => {
  for (const code of API_ERROR_CODES) {
    assert.ok(txt.includes(code), `${code} is not documented`);
  }
});

test('states the access terms so an agent knows there is no signup step', () => {
  assert.match(txt, /no API key|keyless|no account/i);
});

test('every absolute site link resolves to a real route', () => {
  const paths = [...txt.matchAll(new RegExp(`\\]\\(${BASE}([^)]*)\\)`, 'g'))]
    .map(m => m[1].split('?')[0])
    .filter(p => p && p !== '/');

  assert.ok(paths.length > 5);
  for (const path of new Set(paths)) {
    const candidates = [
      `src/app${path}/page.tsx`,
      `src/app${path}/route.ts`,
      // Next's metadata-file convention: /sitemap.xml is generated by
      // src/app/sitemap.ts, /robots.txt by src/app/robots.ts.
      `src/app${path.replace(/\.[^./]+$/, '')}.ts`,
    ];
    assert.ok(
      candidates.some(c => existsSync(resolve(process.cwd(), c))),
      `${path} is linked from llms.txt but has no route`,
    );
  }
});

test('the base URL is normalised, never doubling the slash', () => {
  assert.ok(!buildLlmsTxt('https://example.test/').includes('example.test//'));
});
